### ISSUE TITLE
Error: No "exports" main defined in helia/package.json

### ISSUE THREAD

**Issue by alisolanki** [ipfs/community#778]
I'm trying to import the helia package to snet-sdk-js but seem to get this error:

```
Error: No "exports" main defined in /node_modules/helia/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:294:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:584:13)
    at resolveExports (node:internal/modules/cjs/loader:591:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:668:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1130:27)
    at Function.Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at /Users/alisolanki/mohak/snet-sdk-js/packages/nodejs/dist/core/src/IPFSMetadataProvider.js:27:68
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at IPFSMetadataProvider.HeliaClient (/Users/alisolanki/mohak/snet-sdk-js/packages/nodejs/dist/core/src/IPFSMetadataProvider.js:27:9)
    at IPFSMetadataProvider._constructHeliaClient (/Users/alisolanki/mohak/snet-sdk-js/packages/nodejs/dist/core/src/IPFSMetadataProvider.js:94:25) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

This is how I've imported it:

**IPFSMetadataProvider.js**:
```
import { createHelia as HeliaClient } from "helia";
import { json as HeliaJSON } from "@helia/json";

...

async _constructHeliaClient() {
    const heliaConfig = {
      // Helia-specific configuration
      // Add any additional Helia configurations here
      // This may include libp2p configuration, datastore, etc.
      protocol: this._ipfsEndpoint.protocol.replace(":", ""),
      host: this._ipfsEndpoint.hostname,
      port: this._ipfsEndpoint.port || 5001,
    };
    return await HeliaClient(heliaConfig);
  }
```

**Comment by achingbrain** [comment]
1. `ERR_PACKAGE_PATH_NOT_EXPORTED` is caused when your environment doesn't support [package-exports](https://nodejs.org/api/packages.html#exports), you may need to update node to LTS or Current
2. `createHelia` does not accept `protocol`, `host` or `port` args, since they are in the code above, I think you are upgrading from [ipfs-http-client](https://npmjs.com/package/ipfs-http-client) - if this is the case you should switch to [kubo-rpc-client](https://www.npmjs.com/package/kubo-rpc-client) which is a drop-in replacement

If you are still having problems, please start a discussion on https://discuss.ipfs.tech/ - this repo is for discussing IPFS community standards
